### ISSUE TITLE
Feature request: ability to execute custom SQL before debugging

### ISSUE THREAD

**Issue by ukolovda** [ng-galien/idea-plpgdebugger#6]
**Is your feature request related to a problem? Please describe.**

I use PGTT https://github.com/darold/pgtt extension, and it require load it's module after new session started:
`LOAD '$libdir/plugins/pgtt';`
https://github.com/darold/pgtt#use-of-the-extension

When I start debugging, I should load this module before debugging.
I try use "Evaluate expression" window, but it, seems, not worked (PostgreSQL 14.1), show nothing.

**Describe the solution you'd like**
Allow execute `LOAD 'module'` in the variables

**Describe alternatives you've considered**
Make separate function for initialize and load module. Execute function once in `Variables` block.

**Additional context**

**Comment by ng-galien** [comment]
We have to implements a configuration for the plugin, there is others parameters we can put on it.
Your suggestion to run a statement on the debugging session can be implemented in two ways.

- Plugin level, with a configuration entry
- Debug configuration level

Evaluation is not yet implemented

**Comment by ukolovda** [comment]
Thank you!
Now I can alse avoid this problem: create other `test` procedure with initialization and call of debugging routine.

**Comment by ng-galien** [comment]
Since 1.1.1 you can set it in the config panel. Because there are two session, the calling session and the debugger session, there are two parameters.
In the next future parameters(and timeouts) will be moved at project level.
If you encounter other issues with the debugger and it's related to queries (for function search or data grabbing), you can also try to customise it in the config panel.
I will write a documentation for that.
